openapi: 3.0.2
info:
  version: 1.3.43
  title: Lane State API
  contact:
    email: support@netsolapp.io, support@appexnow.com
  x-logo:
    url: ../lane/docs/64x64.png
    altText: Lane
    backgroundColor: '#FFFFFF'
  description: Lane offers a feature-rich, end-to-end order management system for asset leasing, loans and credit companies. Our platform covers all aspects, from conducting end-to-end sales to performing dealer and partner-related tasks and marketing-related activities.
servers:
- url: https://dms-api.netsolapp.io
tags:
- name: State
paths:
  /dms/state:
    get:
      tags:
      - State
      summary: Get All States
      operationId: get_all_states_dms_state_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - APIKeyHeader: []
      - OAuth2PasswordBearer: []
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-Api-Key
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /signup/verify-otp
externalDocs:
  url: https://developer.appexnow.com/docs/lane/overview
  description: Product Documentation
